Feature: Add differntiation between SNAPSHOT and main version

diff --git a/.github/workflows/schedule.yaml b/.github/workflows/schedule.yaml
--- a/.github/workflows/schedule.yaml
+++ b/.github/workflows/schedule.yaml
@@ -38,12 +38,36 @@ jobs:
             echo "Package not found."
             LATEST_PUSHED_RELEASE=""
         elif [ "$status_code" -eq 200 ]; then
-            # Extract the latest tag from the saved response
-            LATEST_PUSHED_RELEASE=$(cat response.json | jq -r '.[0].name')
-            echo "Latest tag is: $LATEST_PUSHED_RELEASE"
+            if [ ${{contains(github.ref, 'develop')}} ]; then
+              echo "Looking for a SNAPSHOT version in the released packages"
+              for RELEASE_NR in 0 1 .. 10
+              do
+                LATEST_PUSHED_RELEASE=$(cat response.json | jq -r '.[$RELEASE_NR].name')
+                if [[ ${LATEST_PUSHED_RELEASE} == *"SNAPSHOT"*]]; then
+                  echo "Found Latest release ${LATEST_PUSHED_RELEASE}. Continuing ..."
+                  break
+                else
+                  echo "Found Latest release ${LATEST_PUSHED_RELEASE}. Not a SNAPSHOT, looking for SNAPSHOT release ..."
+                fi
+            elif [ ${{contains(github.ref, 'main')}} ]; then
+              echo "Looking for main release version"
+              for RELEASE_NR in 0 1 .. 10
+              do
+                LATEST_PUSHED_RELEASE=$(cat response.json | jq -r '.[$RELEASE_NR].name')
+                if [[ ${LATEST_PUSHED_RELEASE} == *"SNAPSHOT"*]]; then
+                  echo "Found Latest release ${LATEST_PUSHED_RELEASE}. Is a SNAPSHOT, looking for non SNAPSHOT release ..."
+                else
+                  echo "Found Latest release ${LATEST_PUSHED_RELEASE}. Continuing ..."
+                  break
+                fi
+              fi
         else
             echo "Unexpected HTTP status code: $status_code"
             exit 1
+        fi
+        if [[-z ${LATEST_PUSHED_RELEASE} ]]; then
+          echo "Could not find any latest version, aborting"
+          exit 2
         fi
         echo "LATEST_PUSHED_RELEASE=$LATEST_PUSHED_RELEASE" >> $GITHUB_ENV
 
