Refactoring: Add fault tolerance to schedule for image build

diff --git a/.github/workflows/schedule.yaml b/.github/workflows/schedule.yaml
--- a/.github/workflows/schedule.yaml
+++ b/.github/workflows/schedule.yaml
@@ -28,14 +28,24 @@ jobs:
         done
 
         echo "Checking the latest version on GHCR"
-        #TODO: CHECK íf the URL is correct and jq works
-        LATEST_PUSHED_RELEASE=$(curl -H "Authorization: Bearer ${{secrets.ACCESS_TOKEN}}" https://ghcr.io/v2/EMCL-Research-ITSecLab/rosenpass-docker/tags/list | jq -r .[0].version)
-        echo "$LATEST_PUSHED_RELEASE" >> $GITHUB_ENV
-        if [ -z "${LATEST_PUSHED_RELEASE}" ] || [ "${LATEST_PUSHED_RELEASE}" == "null" ]; then
-          echo "No release found"
+
+        ORG_NAME="EMCL-Research-ITSecLab"
+        PACKAGE_NAME="rosenpass"
+                
+        # Fetch latest tags
+        status_code=$(curl -s -w "%{http_code}" -o response.json -H "Authorization: bearer ${{secrets.ACCESS_TOKEN}}" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/orgs/$ORG_NAME/packages/container/$PACKAGE_NAME/versions")
+        if [ "$status_code" -eq 404 ]; then
+            echo "Package not found."
+            LATEST_PUSHED_RELEASE=""
+        elif [ "$status_code" -eq 200 ]; then
+            # Extract the latest tag from the saved response
+            LATEST_PUSHED_RELEASE=$(cat response.json | jq -r '.[0].name')
+            echo "Latest tag is: $LATEST_PUSHED_RELEASE"
         else
-          echo "found latests release with version $LATEST_PUSHED_RELEASE"
+            echo "Unexpected HTTP status code: $status_code"
+            exit 1
         fi
+        echo "$LATEST_PUSHED_RELEASE" >> $GITHUB_ENV
 
         echo "comparing the latest official release with the latest release published by us"
         if [ "${RELEASE}" == "${LATEST_PUSHED_RELEASE}" ]; then
@@ -44,14 +54,10 @@ jobs:
         else
           echo "New version: $RELEASE"
           echo "Latest version built: $LATEST_PUSHED_RELEASE"
-          echo "building new version"
+          echo "Trigger build for new version"
+          curl -X POST \
+          -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
+          -H "Accept: application/vnd.github.v3+json" \
+          https://api.github.com/repos/${{ github.repository }}/actions/workflows/build.yml/dispatches \
+          -d '{"ref":"develop","inputs":{"version":"$RELEASE"}}'
         fi
-
-
-    - name: Trigger build workflow
-      run: |
-        curl -X POST \
-        -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
-        -H "Accept: application/vnd.github.v3+json" \
-        https://api.github.com/repos/${{ github.repository }}/actions/workflows/build.yml/dispatches \
-        -d '{"ref":"develop","inputs":{"version":"$RELEASE"}}'
